# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add Terraform.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Mussrat - Free Trial(f6a7adc2-197c-4935-8b0c-2a8b39cc51b7)'
    backendAzureRmResourceGroupName: 'MainRG'
    backendAzureRmStorageAccountName: 'mibtfstate'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'dev.terraform.tfstate'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: -lock=false -input=false

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: -lock=false -input=false